name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Dependencies for Ubuntu
        # git >= 2.18 required for actions/checkout git support
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt update
          apt install -y git build-essential clang python3 libssl-dev libkrb5-dev libc++-dev
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npx oclif pack
      -
        name: Pack Tarballs
        run: npx oclif pack:tarballs
      - 
        name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
