name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y libstdc++-4.9-dev
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npx oclif pack
      -
        name: Pack Tarballs
        run: npx oclif pack:tarballs
      - 
        name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
